spring:
  datasource:
    url: jdbc:h2:mem:member
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true

  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: false
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}