server:
  port: 7077
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ddobak?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${SERVER_MYSQL_USERNAME}
    password: ${SERVER_MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: false
      host: redis
      port: 6377
      password: ${REDIS_PASSWORD}
# deploy test