server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  token:
    secret: ${JWT_SECRET_KEY}

