spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ddobak?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
S
  cache:
    type: redis
    redis:
      time-to-live: 3600
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}


