spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddobak?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: false
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}