INSERT INTO ddobak.member ( created_at, modified_at, email, login_password, introduce_text, nickname, production_status, profile_img, sign_up_type, point) VALUES ( '2023-11-07 11:36:31.297964', '2023-11-07 11:36:31.297964', 'lkm454545@gmail.com', '$2a$10$pe2MOCxUmklNMBLPQ9fUluEQqzws2Ef6q0dTGtqmowOtu1s.BkB92', '안녕하세요! 이도하입니다.', '이도하', 0, '', 'GENERAL',0);
INSERT INTO ddobak.member ( created_at, modified_at, email, login_password, introduce_text, nickname, production_status, profile_img, sign_up_type, point) VALUES ( '2023-11-07 11:36:31.297964', '2023-11-07 11:36:31.297964', 'user2@example.com', '$2a$10$pe2MOCxUmklNMBLPQ9fUluEQqzws2Ef6q0dTGtqmowOtu1s.BkB92', 'User 2', 'user2', 0, '', 'GENERAL',0);
INSERT INTO ddobak.member ( created_at, modified_at, email, login_password, introduce_text, nickname, production_status, profile_img, sign_up_type, point) VALUES( '2023-11-07 11:36:31.297964', '2023-11-07 11:36:31.297964', 'user3@example.com', '$2a$10$pe2MOCxUmklNMBLPQ9fUluEQqzws2Ef6q0dTGtqmowOtu1s.BkB92', 'User 3', 'user3', 0, '', 'GENERAL',0);
INSERT INTO ddobak.member ( created_at, modified_at, email, login_password, introduce_text, nickname, production_status, profile_img, sign_up_type, point) VALUES( '2023-11-07 11:36:31.297964', '2023-11-07 11:36:31.297964', 'user4@example.com', '$2a$10$pe2MOCxUmklNMBLPQ9fUluEQqzws2Ef6q0dTGtqmowOtu1s.BkB92', 'User 4', 'user4', 0, '', 'GENERAL',0);
INSERT INTO ddobak.member ( created_at, modified_at, email, login_password, introduce_text, nickname, production_status, profile_img, sign_up_type, point) VALUES( '2023-11-07 11:36:31.297964', '2023-11-07 11:36:31.297964', 'user5@example.com', '$2a$10$pe2MOCxUmklNMBLPQ9fUluEQqzws2Ef6q0dTGtqmowOtu1s.BkB92', 'User 5', 'user5', 0, '', 'GENERAL',0);

INSERT INTO ddobak.font (created_at, modified_at, commerce_status, copyrigher, copyright_notice, create_date, eng_font_name, font_file_url, font_sort_url, free_status, introduce_text, kor_font_name, open_status, price, same_person_check, view_count, producer) VALUES (NOW(), NOW(), 0, 'Copyrighter 1', 1, DATE(NOW()), 'English Font 1', 'font_file_url_1', 'font_sort_url_1', 1, 'Introduce text for Font 1', 'Korean Font 1', 1, 1000, 1, 0, 1);
INSERT INTO ddobak.font (created_at, modified_at, commerce_status, copyrigher, copyright_notice, create_date, eng_font_name, font_file_url, font_sort_url, free_status, introduce_text, kor_font_name, open_status, price, same_person_check, view_count, producer) VALUES (NOW(), NOW(), 1, 'Copyrighter 2', 0, DATE(NOW()), 'English Font 2', 'font_file_url_2', 'font_sort_url_2', 0, 'Introduce text for Font 2', 'Korean Font 2', 0, 2000, 1, 0, 1);
INSERT INTO ddobak.font (created_at, modified_at, commerce_status, copyrigher, copyright_notice, create_date, eng_font_name, font_file_url, font_sort_url, free_status, introduce_text, kor_font_name, open_status, price, same_person_check, view_count, producer) VALUES (NOW(), NOW(), 0, 'Copyrighter 3', 1, DATE(NOW()), 'English Font 3', 'font_file_url_3', 'font_sort_url_3', 1, 'Introduce text for Font 3', 'Korean Font 3', 1, 1500, 0, 0, 2);
INSERT INTO ddobak.font (created_at, modified_at, commerce_status, copyrigher, copyright_notice, create_date, eng_font_name, font_file_url, font_sort_url, free_status, introduce_text, kor_font_name, open_status, price, same_person_check, view_count, producer) VALUES (NOW(), NOW(), 1, 'Copyrighter 4', 0, DATE(NOW()), 'English Font 4', 'font_file_url_4', 'font_sort_url_4', 0, 'Introduce text for Font 4', 'Korean Font 4', 0, 1800, 1, 0, 2);
INSERT INTO ddobak.font (created_at, modified_at, commerce_status, copyrigher, copyright_notice, create_date, eng_font_name, font_file_url, font_sort_url, free_status, introduce_text, kor_font_name, open_status, price, same_person_check, view_count, producer) VALUES (NOW(), NOW(), 0, 'Copyrighter 5', 1, DATE(NOW()), 'English Font 5', 'font_file_url_5', 'font_sort_url_5', 1, 'Introduce text for Font 5', 'Korean Font 5', 1, 1200, 0, 0, 3);
INSERT INTO ddobak.font (created_at, modified_at, commerce_status, copyrigher, copyright_notice, create_date, eng_font_name, font_file_url, font_sort_url, free_status, introduce_text, kor_font_name, open_status, price, same_person_check, view_count, producer) VALUES (NOW(), NOW(), 1, 'Copyrighter 6', 0, DATE(NOW()), 'English Font 6', 'font_file_url_6', 'font_sort_url_6', 0, 'Introduce text for Font 6', 'Korean Font 6', 0, 2200, 1, 0, 3);
INSERT INTO ddobak.font (created_at, modified_at, commerce_status, copyrigher, copyright_notice, create_date, eng_font_name, font_file_url, font_sort_url, free_status, introduce_text, kor_font_name, open_status, price, same_person_check, view_count, producer) VALUES (NOW(), NOW(), 0, 'Copyrighter 7', 1, DATE(NOW()), 'English Font 7', 'font_file_url_7', 'font_sort_url_7', 1, 'Introduce text for Font 7', 'Korean Font 7', 1, 1300, 0, 0, 4);
INSERT INTO ddobak.font (created_at, modified_at, commerce_status, copyrigher, copyright_notice, create_date, eng_font_name, font_file_url, font_sort_url, free_status, introduce_text, kor_font_name, open_status, price, same_person_check, view_count, producer) VALUES (NOW(), NOW(), 1, 'Copyrighter 8', 0, DATE(NOW()), 'English Font 8', 'font_file_url_8', 'font_sort_url_8', 0, 'Introduce text for Font 8', 'Korean Font 8', 0, 2500, 1, 0, 4);
INSERT INTO ddobak.font (created_at, modified_at, commerce_status, copyrigher, copyright_notice, create_date, eng_font_name, font_file_url, font_sort_url, free_status, introduce_text, kor_font_name, open_status, price, same_person_check, view_count, producer) VALUES (NOW(), NOW(), 0, 'Copyrighter 9', 1, DATE(NOW()), 'English Font 9', 'font_file_url_9', 'font_sort_url_9', 1, 'Introduce text for Font 9', 'Korean Font 9', 1, 1600, 0, 0, 5);
INSERT INTO ddobak.font (created_at, modified_at, commerce_status, copyrigher, copyright_notice, create_date, eng_font_name, font_file_url, font_sort_url, free_status, introduce_text, kor_font_name, open_status, price, same_person_check, view_count, producer) VALUES (NOW(), NOW(), 1, 'Copyrighter 10', 0, DATE(NOW()), 'English Font 10', 'font_file_url_10', 'font_sort_url_10', 0, 'Introduce text for Font 10', 'Korean Font 10', 0, 3000, 1, 0, 5);
